name: Java CD

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
       
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@2.0.1
        
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      
      - name: Validate version
        run: mvn -B validate 
        
      - name: Deploy to GitHub packages
         # Have to skip doc and sources because GH Packages doesn't support classifiers
        run: mvn -B deploy -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
